In [2]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [4]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr[1:5:2])


[2 4]


In [5]:
import numpy as np

arr = np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


In [6]:
import numpy as np

arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


In [7]:
import numpy as np

arr = np.array([15, 40, 8, 25])

print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Maximum: 40
Minimum: 8
