In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(np.mean(arr))

25.0


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr[0])
print(arr[2])

10
30


In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])

[20 30 40]


In [5]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)

(2, 3)
